/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\尚硅谷前端\\项目源码\\vuepress-demo\\vuepress-AllenDOCS\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-3bc25933",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3bc25933").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-106693fb",
    path: "/views/Work/ChengDouKeJi/Problem.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-106693fb").then(next)
    },
  },
  {
    name: "v-e7375c4a",
    path: "/views/Work/ChengDouKeJi/ceshi.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e7375c4a").then(next)
    },
  },
  {
    name: "v-2dc6f4f4",
    path: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/CSS/CSS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2dc6f4f4").then(next)
    },
  },
  {
    path: "/views/前端基础/CSS/CSS.html",
    redirect: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/CSS/CSS.html"
  },
  {
    path: "/views/前端基础/CSS/CSS.html",
    redirect: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/CSS/CSS.html"
  },
  {
    name: "v-db44056c",
    path: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/HTML/html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-db44056c").then(next)
    },
  },
  {
    path: "/views/前端基础/HTML/html.html",
    redirect: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/HTML/html.html"
  },
  {
    path: "/views/前端基础/HTML/html.html",
    redirect: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/HTML/html.html"
  },
  {
    name: "v-399b5148",
    path: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/HTML/wenzhang.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-399b5148").then(next)
    },
  },
  {
    path: "/views/前端基础/HTML/wenzhang.html",
    redirect: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/HTML/wenzhang.html"
  },
  {
    path: "/views/前端基础/HTML/wenzhang.html",
    redirect: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/HTML/wenzhang.html"
  },
  {
    name: "v-a67119ec",
    path: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/JavaScript/JavaScript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a67119ec").then(next)
    },
  },
  {
    path: "/views/前端基础/JavaScript/JavaScript.html",
    redirect: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/JavaScript/JavaScript.html"
  },
  {
    path: "/views/前端基础/JavaScript/JavaScript.html",
    redirect: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/JavaScript/JavaScript.html"
  },
  {
    name: "v-f95fe9ee",
    path: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/JavaScript/JavaScript%E8%AF%8D%E6%B1%87.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f95fe9ee").then(next)
    },
  },
  {
    path: "/views/前端基础/JavaScript/JavaScript词汇.html",
    redirect: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/JavaScript/JavaScript%E8%AF%8D%E6%B1%87.html"
  },
  {
    path: "/views/前端基础/JavaScript/JavaScript词汇.html",
    redirect: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/JavaScript/JavaScript%E8%AF%8D%E6%B1%87.html"
  },
  {
    name: "v-47f23fca",
    path: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/jQuery/jQuery.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47f23fca").then(next)
    },
  },
  {
    path: "/views/前端基础/jQuery/jQuery.html",
    redirect: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/jQuery/jQuery.html"
  },
  {
    path: "/views/前端基础/jQuery/jQuery.html",
    redirect: "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/jQuery/jQuery.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-168d2a98",
    path: "/tag/Work/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-168d2a98").then(next)
    },
    meta: {"pid":"tags","id":"Work"}
  },
  {
    path: "/tag/Work/index.html",
    redirect: "/tag/Work/"
  },
  {
    name: "v-0cf0fa4a",
    path: "/tag/ChengDouKeJi/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0cf0fa4a").then(next)
    },
    meta: {"pid":"tags","id":"ChengDouKeJi"}
  },
  {
    path: "/tag/ChengDouKeJi/index.html",
    redirect: "/tag/ChengDouKeJi/"
  },
  {
    name: "v-1a10f9dc",
    path: "/tag/前端基础/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1a10f9dc").then(next)
    },
    meta: {"pid":"tags","id":"前端基础"}
  },
  {
    path: "/tag/前端基础/index.html",
    redirect: "/tag/前端基础/"
  },
  {
    name: "v-3259a754",
    path: "/tag/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3259a754").then(next)
    },
    meta: {"pid":"tags","id":"CSS"}
  },
  {
    path: "/tag/CSS/index.html",
    redirect: "/tag/CSS/"
  },
  {
    name: "v-184d950c",
    path: "/tag/HTML/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-184d950c").then(next)
    },
    meta: {"pid":"tags","id":"HTML"}
  },
  {
    path: "/tag/HTML/index.html",
    redirect: "/tag/HTML/"
  },
  {
    name: "v-7a5f6990",
    path: "/tag/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7a5f6990").then(next)
    },
    meta: {"pid":"tags","id":"JavaScript"}
  },
  {
    path: "/tag/JavaScript/index.html",
    redirect: "/tag/JavaScript/"
  },
  {
    name: "v-66172787",
    path: "/tag/jQuery/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-66172787").then(next)
    },
    meta: {"pid":"tags","id":"jQuery"}
  },
  {
    path: "/tag/jQuery/index.html",
    redirect: "/tag/jQuery/"
  },
  {
    name: "v-61f540c0",
    path: "/categories/Work/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-61f540c0").then(next)
    },
    meta: {"pid":"categories","id":"Work"}
  },
  {
    path: "/categories/Work/index.html",
    redirect: "/categories/Work/"
  },
  {
    name: "v-1d0fadc4",
    path: "/categories/前端基础/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-1d0fadc4").then(next)
    },
    meta: {"pid":"categories","id":"前端基础"}
  },
  {
    path: "/categories/前端基础/index.html",
    redirect: "/categories/前端基础/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]