/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Allen帮助文档",
  "description": "java,Vue，前端，后端帮助文档",
  "base": "/VuePress-AllenDocs/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/VuePress-AllenDocs/images/favicon.svg"
      }
    ],
    [
      "meta",
      {
        "name": "Allen",
        "content": "Allen帮助档"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "Vue,java,前端，后端帮助文档"
      }
    ],
    [
      "script",
      {},
      "var _hmt = _hmt || [];\n    (function() {\n      var hm = document.createElement(\"script\");\n      hm.src = \"https://hm.baidu.com/hm.js?668842dc21c1b8f215b000531ec8f69e\";\n      var s = document.getElementsByTagName(\"script\")[0]; \n      s.parentNode.insertBefore(hm, s);\n    })();"
    ],
    [
      "script",
      {
        "src": "/VuePress-AllenDocs/utils/js/jq3.5.1.js"
      },
      ""
    ],
    [
      "script",
      {
        "src": "/VuePress-AllenDocs/utils/js/click.js"
      },
      ""
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "tagline": "学而至上~",
        "heroText": "Allen",
        "bgImageStyle": {
          "height": "100vh"
        },
        "heroTextStyle": {
          "color": "#fff"
        },
        "bgImage": "/images/bg-logo.svg",
        "isShowTitleInHome": false,
        "readingShow": "top"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3bc25933",
      "path": "/"
    },
    {
      "title": "橙都常见问题解决方法",
      "frontmatter": {
        "title": "橙都常见问题解决方法",
        "date": "2023-05-17T22:57:00.000Z",
        "sidebar": "auto",
        "categories": [
          "Work"
        ],
        "tags": [
          "Work",
          "ChengDouKeJi"
        ],
        "keys": [
          "d8d9ac0a7a226829c61059d1862e5c4f"
        ],
        "sticky": 5,
        "readingShow": "top"
      },
      "regularPath": "/views/Work/ChengDouKeJi/Problem.html",
      "relativePath": "views/Work/ChengDouKeJi/Problem.md",
      "key": "v-106693fb",
      "path": "/views/Work/ChengDouKeJi/Problem.html",
      "headers": [
        {
          "level": 2,
          "title": "1.1常见问题与解决方法",
          "slug": "_1-1常见问题与解决方法"
        },
        {
          "level": 3,
          "title": "1.1.1手机号被占用",
          "slug": "_1-1-1手机号被占用"
        },
        {
          "level": 3,
          "title": "1.1.2系统未发放直推佣金",
          "slug": "_1-1-2系统未发放直推佣金"
        },
        {
          "level": 2,
          "title": "1.2技术问题与解决方法",
          "slug": "_1-2技术问题与解决方法"
        },
        {
          "level": 3,
          "title": "1.2.1商户号和小程序违规情况",
          "slug": "_1-2-1商户号和小程序违规情况"
        },
        {
          "level": 3,
          "title": "1.2.3小程序chooseAddress和getLocation接口申请",
          "slug": "_1-2-3小程序chooseaddress和getlocation接口申请"
        },
        {
          "level": 2,
          "title": "1.3售后问题与解决方法",
          "slug": "_1-3售后问题与解决方法"
        },
        {
          "level": 3,
          "title": "1.3.1关于菜品售后问题",
          "slug": "_1-3-1关于菜品售后问题"
        },
        {
          "level": 3,
          "title": "1.3.2关于机器人售后问题",
          "slug": "_1-3-2关于机器人售后问题"
        },
        {
          "level": 3,
          "title": "1.3.3关于商品维权订单问题",
          "slug": "_1-3-3关于商品维权订单问题"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>橙都常见问题解决方法</p>\n</div>"
    },
    {
      "title": "橙都常见问题解决方法",
      "frontmatter": {
        "title": "橙都常见问题解决方法",
        "date": "2023-05-17T22:57:00.000Z",
        "sidebar": "auto",
        "categories": [
          "Work"
        ],
        "tags": [
          "Work",
          "ChengDouKeJi"
        ],
        "publish": false,
        "readingShow": "top"
      },
      "regularPath": "/views/Work/ChengDouKeJi/ceshi.html",
      "relativePath": "views/Work/ChengDouKeJi/ceshi.md",
      "key": "v-e7375c4a",
      "path": "/views/Work/ChengDouKeJi/ceshi.html",
      "headers": [
        {
          "level": 2,
          "title": "标题2",
          "slug": "标题2"
        },
        {
          "level": 3,
          "title": "标题3",
          "slug": "标题3"
        },
        {
          "level": 2,
          "title": "1.1常见问题与解决方法",
          "slug": "_1-1常见问题与解决方法"
        },
        {
          "level": 3,
          "title": "1.1.1手机号被占用",
          "slug": "_1-1-1手机号被占用"
        },
        {
          "level": 3,
          "title": "1.1.2系统未发放直推佣金",
          "slug": "_1-1-2系统未发放直推佣金"
        },
        {
          "level": 2,
          "title": "1.2技术问题与解决方法",
          "slug": "_1-2技术问题与解决方法"
        },
        {
          "level": 3,
          "title": "1.2.1商户号和小程序违规情况",
          "slug": "_1-2-1商户号和小程序违规情况"
        },
        {
          "level": 3,
          "title": "1.2.3小程序chooseAddress和getLocation接口申请",
          "slug": "_1-2-3小程序chooseaddress和getlocation接口申请"
        },
        {
          "level": 2,
          "title": "1.3售后问题与解决方法",
          "slug": "_1-3售后问题与解决方法"
        },
        {
          "level": 3,
          "title": "1.3.1关于菜品售后问题",
          "slug": "_1-3-1关于菜品售后问题"
        },
        {
          "level": 3,
          "title": "1.3.2关于机器人售后问题",
          "slug": "_1-3-2关于机器人售后问题"
        },
        {
          "level": 3,
          "title": "1.3.3关于商品维权订单问题",
          "slug": "_1-3-3关于商品维权订单问题"
        }
      ]
    },
    {
      "title": "css帮助文档",
      "frontmatter": {
        "title": "css帮助文档",
        "date": "2023-05-18T15:31:00.000Z",
        "sidebar": "auto",
        "categories": [
          "前端基础"
        ],
        "tags": [
          "前端基础",
          "CSS"
        ],
        "sticky": 6,
        "readingShow": "top"
      },
      "regularPath": "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/CSS/CSS.html",
      "relativePath": "views/前端基础/CSS/CSS.md",
      "key": "v-2dc6f4f4",
      "path": "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/CSS/CSS.html",
      "headers": [
        {
          "level": 2,
          "title": "层叠样式表（CSS，Cascading Style Sheets）",
          "slug": "层叠样式表-css-cascading-style-sheets"
        },
        {
          "level": 2,
          "title": "选择器（Selector）",
          "slug": "选择器-selector"
        },
        {
          "level": 2,
          "title": "CSS中的伪类（Pseudo-class）",
          "slug": "css中的伪类-pseudo-class"
        },
        {
          "level": 2,
          "title": "伪元素（Pseudo-element）",
          "slug": "伪元素-pseudo-element"
        },
        {
          "level": 2,
          "title": "盒模型（Box Model）",
          "slug": "盒模型-box-model"
        },
        {
          "level": 2,
          "title": "相对单位（Relative Unit）",
          "slug": "相对单位-relative-unit"
        },
        {
          "level": 2,
          "title": "绝对单位（Absolute Unit）",
          "slug": "绝对单位-absolute-unit"
        },
        {
          "level": 2,
          "title": "浮动（Float）",
          "slug": "浮动-float"
        },
        {
          "level": 2,
          "title": "定位（Positioning）",
          "slug": "定位-positioning"
        },
        {
          "level": 2,
          "title": "弹性布局（Flexbox）",
          "slug": "弹性布局-flexbox"
        },
        {
          "level": 2,
          "title": "网格布局（Grid Layout）",
          "slug": "网格布局-grid-layout"
        },
        {
          "level": 2,
          "title": "响应式设计（Responsive Design）",
          "slug": "响应式设计-responsive-design"
        },
        {
          "level": 2,
          "title": "媒体查询（Media Query）",
          "slug": "媒体查询-media-query"
        },
        {
          "level": 2,
          "title": "动画（Animation）",
          "slug": "动画-animation"
        },
        {
          "level": 2,
          "title": "过渡效果（Transition）",
          "slug": "过渡效果-transition"
        },
        {
          "level": 2,
          "title": "字体（Typography）",
          "slug": "字体-typography"
        },
        {
          "level": 2,
          "title": "盒阴影（Box Shadow）",
          "slug": "盒阴影-box-shadow"
        },
        {
          "level": 2,
          "title": "清除浮动（Clearfix）",
          "slug": "清除浮动-clearfix"
        },
        {
          "level": 2,
          "title": "重置样式表（Reset Stylesheet）",
          "slug": "重置样式表-reset-stylesheet"
        }
      ]
    },
    {
      "title": "html帮助文档",
      "frontmatter": {
        "title": "html帮助文档",
        "date": "2023-05-18T12:57:00.000Z",
        "sidebar": "auto",
        "categories": [
          "前端基础"
        ],
        "tags": [
          "前端基础",
          "HTML"
        ],
        "sticky": 6,
        "readingShow": "top"
      },
      "regularPath": "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/HTML/html.html",
      "relativePath": "views/前端基础/HTML/html.md",
      "key": "v-db44056c",
      "path": "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/HTML/html.html",
      "headers": [
        {
          "level": 2,
          "title": "HTML 中的标记语言（Markup Language）",
          "slug": "html-中的标记语言-markup-language"
        },
        {
          "level": 2,
          "title": "HTML 中的元素（Element）",
          "slug": "html-中的元素-element"
        },
        {
          "level": 2,
          "title": "HTML 中的语义化（Semantic）",
          "slug": "html-中的语义化-semantic"
        },
        {
          "level": 2,
          "title": "HTML 中的属性（Attribute）",
          "slug": "html-中的属性-attribute"
        },
        {
          "level": 2,
          "title": "内联元素（Inline Element）",
          "slug": "内联元素-inline-element"
        },
        {
          "level": 2,
          "title": "块级元素（Block-level Element）",
          "slug": "块级元素-block-level-element"
        },
        {
          "level": 2,
          "title": "文档对象模型（DOM，Document Object Model）",
          "slug": "文档对象模型-dom-document-object-model"
        },
        {
          "level": 2,
          "title": "表单（Form）",
          "slug": "表单-form"
        },
        {
          "level": 2,
          "title": "输入字段（Input Field）",
          "slug": "输入字段-input-field"
        },
        {
          "level": 2,
          "title": "标题（Heading）",
          "slug": "标题-heading"
        },
        {
          "level": 2,
          "title": "段落（Paragraph）",
          "slug": "段落-paragraph"
        },
        {
          "level": 2,
          "title": "链接（Link）",
          "slug": "链接-link"
        },
        {
          "level": 2,
          "title": "图像（Image）",
          "slug": "图像-image"
        },
        {
          "level": 2,
          "title": "列表（List）",
          "slug": "列表-list"
        },
        {
          "level": 2,
          "title": "表格（Table）",
          "slug": "表格-table"
        },
        {
          "level": 2,
          "title": "框架 （iFrame）",
          "slug": "框架-iframe"
        },
        {
          "level": 2,
          "title": "注释（Comment）",
          "slug": "注释-comment"
        }
      ]
    },
    {
      "frontmatter": {
        "readingShow": "top"
      },
      "regularPath": "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/HTML/wenzhang.html",
      "relativePath": "views/前端基础/HTML/wenzhang.md",
      "key": "v-399b5148",
      "path": "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/HTML/wenzhang.html"
    },
    {
      "title": "JavaScript帮助文档",
      "frontmatter": {
        "title": "JavaScript帮助文档",
        "date": "2023-05-18T17:16:00.000Z",
        "sidebar": "auto",
        "categories": [
          "前端基础"
        ],
        "tags": [
          "前端基础",
          "JavaScript"
        ],
        "sticky": 6,
        "readingShow": "top"
      },
      "regularPath": "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/JavaScript/JavaScript.html",
      "relativePath": "views/前端基础/JavaScript/JavaScript.md",
      "key": "v-a67119ec",
      "path": "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/JavaScript/JavaScript.html",
      "headers": [
        {
          "level": 2,
          "title": "JavaScript常用30个方法",
          "slug": "javascript常用30个方法"
        },
        {
          "level": 2,
          "title": "JavaScript30个常用的读取和修改css样式",
          "slug": "javascript30个常用的读取和修改css样式"
        },
        {
          "level": 2,
          "title": "变量（Variable）",
          "slug": "变量-variable"
        },
        {
          "level": 2,
          "title": "数据类型（Data types）",
          "slug": "数据类型-data-types"
        },
        {
          "level": 2,
          "title": "条件语句（Conditional statements）",
          "slug": "条件语句-conditional-statements"
        },
        {
          "level": 2,
          "title": "循环语句（Loop statements）",
          "slug": "循环语句-loop-statements"
        },
        {
          "level": 2,
          "title": "函数（Function）",
          "slug": "函数-function"
        },
        {
          "level": 2,
          "title": "对象（Object）",
          "slug": "对象-object"
        },
        {
          "level": 2,
          "title": "数组（Array）",
          "slug": "数组-array"
        },
        {
          "level": 2,
          "title": "事件（Event）",
          "slug": "事件-event"
        },
        {
          "level": 2,
          "title": "DOM操作（DOM manipulation）",
          "slug": "dom操作-dom-manipulation"
        },
        {
          "level": 2,
          "title": "AJAX",
          "slug": "ajax"
        },
        {
          "level": 2,
          "title": "JSON",
          "slug": "json"
        },
        {
          "level": 2,
          "title": "异步编程",
          "slug": "异步编程"
        },
        {
          "level": 2,
          "title": "闭包（Closure）",
          "slug": "闭包-closure"
        },
        {
          "level": 2,
          "title": "原型（Prototype）",
          "slug": "原型-prototype"
        },
        {
          "level": 2,
          "title": "模块化（Modularity） -->",
          "slug": "模块化-modularity"
        },
        {
          "level": 2,
          "title": "正则表达式（Regular expression）",
          "slug": "正则表达式-regular-expression"
        },
        {
          "level": 3,
          "title": "正则表达式基本介绍",
          "slug": "正则表达式基本介绍"
        },
        {
          "level": 3,
          "title": "正则表达式匹配规则",
          "slug": "正则表达式匹配规则"
        },
        {
          "level": 2,
          "title": "错误处理（Error handling）",
          "slug": "错误处理-error-handling"
        },
        {
          "level": 2,
          "title": "ES6及以上版本（ES6+）",
          "slug": "es6及以上版本-es6"
        },
        {
          "level": 2,
          "title": "箭头函数（Arrow function）",
          "slug": "箭头函数-arrow-function"
        },
        {
          "level": 2,
          "title": "Promise",
          "slug": "promise"
        },
        {
          "level": 2,
          "title": "迭代器（Iterator）",
          "slug": "迭代器-iterator"
        },
        {
          "level": 2,
          "title": "生成器（Generator）",
          "slug": "生成器-generator"
        },
        {
          "level": 2,
          "title": "async/await",
          "slug": "async-await"
        }
      ]
    },
    {
      "frontmatter": {
        "readingShow": "top"
      },
      "regularPath": "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/JavaScript/JavaScript%E8%AF%8D%E6%B1%87.html",
      "relativePath": "views/前端基础/JavaScript/JavaScript词汇.md",
      "key": "v-f95fe9ee",
      "path": "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/JavaScript/JavaScript%E8%AF%8D%E6%B1%87.html"
    },
    {
      "title": "jQuery帮助文档",
      "frontmatter": {
        "title": "jQuery帮助文档",
        "date": "2023-05-19T10:31:00.000Z",
        "sidebar": "auto",
        "categories": [
          "前端基础"
        ],
        "tags": [
          "前端基础",
          "jQuery"
        ],
        "sticky": 6,
        "readingShow": "top"
      },
      "regularPath": "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/jQuery/jQuery.html",
      "relativePath": "views/前端基础/jQuery/jQuery.md",
      "key": "v-47f23fca",
      "path": "/views/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/jQuery/jQuery.html",
      "headers": [
        {
          "level": 2,
          "title": "测试",
          "slug": "测试"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline",
        "readingShow": "top"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Work Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/Work/",
      "key": "v-168d2a98",
      "path": "/tag/Work/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "ChengDouKeJi Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/ChengDouKeJi/",
      "key": "v-0cf0fa4a",
      "path": "/tag/ChengDouKeJi/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "前端基础 Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/",
      "key": "v-1a10f9dc",
      "path": "/tag/前端基础/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "CSS Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/CSS/",
      "key": "v-3259a754",
      "path": "/tag/CSS/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "HTML Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/HTML/",
      "key": "v-184d950c",
      "path": "/tag/HTML/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JavaScript Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/JavaScript/",
      "key": "v-7a5f6990",
      "path": "/tag/JavaScript/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "jQuery Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/jQuery/",
      "key": "v-66172787",
      "path": "/tag/jQuery/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Work Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/Work/",
      "key": "v-61f540c0",
      "path": "/categories/Work/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端基础 Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80/",
      "key": "v-1d0fadc4",
      "path": "/categories/前端基础/"
    }
  ],
  "themeConfig": {
    "keyPage": {
      "color": "#42b983",
      "lineColor": "#42b983"
    },
    "type": "blog",
    "fullscreen": true,
    "logo": "/images/favicon.svg",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "subSidebar": "auto",
    "sidebar": "auto",
    "author": "Allen",
    "authorAvatar": "/images/avatar.svg",
    "mode": "light",
    "codeTheme": "tomorrow",
    "record": "蜀ICP备20019955号",
    "recordLink": "https://icp.chinaz.com/home/info?host=pengsir.top",
    "smooth": "true",
    "lastUpdated": "最后更新时间于",
    "friendLink": [
      {
        "title": "午后南杂",
        "desc": "Enjoy when you can, and endure when you must.",
        "email": "recoluan@qq.com",
        "link": "https://www.recoluan.com"
      },
      {
        "title": "唐子涵的博客",
        "desc": "至于未来会怎么样 反正路还长 天总会亮",
        "link": "https://www.zihanzy.com/"
      },
      {
        "title": "李Sir的博客",
        "desc": "活在当下",
        "link": "https://heroli.netlify.app/"
      }
    ],
    "nav": [
      {
        "text": "主页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "工具箱",
        "icon": "iconfont icon-tools",
        "items": [
          {
            "text": "在线PS",
            "link": "https://www.uupoop.com/"
          },
          {
            "text": "奶牛快传",
            "link": "https://cowtransfer.com/"
          },
          {
            "text": "编程语言排行榜",
            "link": "https://www.tiobe.com/tiobe-index/"
          }
        ]
      },
      {
        "text": "时间线",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "关于",
        "icon": "reco-message",
        "items": [
          {
            "text": "关于我",
            "link": "/views/About/author",
            "icon": "reco-account"
          },
          {
            "text": "简历",
            "link": "/views/About/resume",
            "icon": "reco-document"
          },
          {
            "text": "CSDN",
            "link": "https://blog.csdn.net/weixin_43742708",
            "icon": "reco-csdn"
          },
          {
            "text": "GitHub",
            "link": "https://github.com/penggang-home",
            "icon": "reco-github"
          },
          {
            "text": "Gitee",
            "link": "https://gitee.com/penggang-home",
            "icon": "reco-mayun"
          }
        ]
      }
    ]
  }
}