/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Work": {
      "key": "Work",
      "scope": "tags",
      "path": "/tag/Work/",
      "pageKeys": [
        "v-106693fb",
        "v-e7375c4a"
      ]
    },
    "ChengDouKeJi": {
      "key": "ChengDouKeJi",
      "scope": "tags",
      "path": "/tag/ChengDouKeJi/",
      "pageKeys": [
        "v-106693fb",
        "v-e7375c4a"
      ]
    },
    "前端基础": {
      "key": "前端基础",
      "scope": "tags",
      "path": "/tag/前端基础/",
      "pageKeys": [
        "v-2dc6f4f4",
        "v-db44056c",
        "v-a67119ec",
        "v-47f23fca"
      ]
    },
    "CSS": {
      "key": "CSS",
      "scope": "tags",
      "path": "/tag/CSS/",
      "pageKeys": [
        "v-2dc6f4f4"
      ]
    },
    "HTML": {
      "key": "HTML",
      "scope": "tags",
      "path": "/tag/HTML/",
      "pageKeys": [
        "v-db44056c"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-a67119ec"
      ]
    },
    "jQuery": {
      "key": "jQuery",
      "scope": "tags",
      "path": "/tag/jQuery/",
      "pageKeys": [
        "v-47f23fca"
      ]
    }
  },
  "categories": {
    "Work": {
      "key": "Work",
      "scope": "categories",
      "path": "/categories/Work/",
      "pageKeys": [
        "v-106693fb",
        "v-e7375c4a"
      ]
    },
    "前端基础": {
      "key": "前端基础",
      "scope": "categories",
      "path": "/categories/前端基础/",
      "pageKeys": [
        "v-2dc6f4f4",
        "v-db44056c",
        "v-a67119ec",
        "v-47f23fca"
      ]
    }
  },
  "timeline": {}
}