/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "Work",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/Work/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "ChengDouKeJi",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/ChengDouKeJi/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "前端基础",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/前端基础/","interval":[0,4]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "CSS",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/CSS/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "HTML",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/HTML/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "JavaScript",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/JavaScript/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "jQuery",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/jQuery/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "Work",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/Work/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "前端基础",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/前端基础/","interval":[0,4]}],
  prevText: "Prev",
  nextText: "Next",
}]